spring.application.name=contratistas-csv
logging.file.name=resultado/proceso.log
logging.level.root=INFO
app.endpoint=https://jsonplaceholder.typicode.com/users
app.fallback-json=model/Contratistas.json
app.output-csv=resultado/Contratistas.csv
app.domain=democompany.com